export interface FeatureDoc {
    name: string
    /** UIページがない機能（バックグラウンド実行のみ）は省略 */
    href?: string
    category: string
    description: string
    capabilities: string[]
    metrics?: string[]
    ai?: boolean
    apiRoute?: string
}

export const FEATURE_CATEGORIES = [
    'ユーザー分析',
    '経路・離脱分析',
    'コンバージョン・ファネル',
    'ABテスト',
    'レポート・データ',
] as const

export const FEATURE_LIST: FeatureDoc[] = [
    // ── ユーザー分析 ──
    {
        name: 'ユーザー行動タイムライン',
        href: '/user',
        category: 'ユーザー分析',
        description: 'user_pseudo_id を指定すると、そのユーザーが「いつ・どのページを見て・何を操作したか」を時系列で表示します。施策後の個別確認や CS 対応に活用できます。',
        capabilities: [
            'user_pseudo_id によるユーザー絞り込み',
            '日付グループ別イベントタイムライン',
            'ページビュー・クリック・セッション開始などのイベント種別表示',
            'ページタイトル・パラメータの確認',
        ],
        metrics: ['activeUsers', 'eventName', 'pagePath', 'pageTitle'],
        apiRoute: 'POST /api/user/timeline',
    },
    {
        name: 'ユーザーリスト・セグメントビルダー',
        href: '/user/segment-builder',
        category: 'ユーザー分析',
        description: 'デバイス・流入元・PV数などの条件を組み合わせてユーザーをフィルタリングし、該当ユーザー数と行動傾向を確認します。CRM 連携やリターゲティング施策の対象絞り込みに使います。',
        capabilities: [
            '複数条件の AND 絞り込み',
            'デバイス / OS / ブラウザ / 流入元 / 国 での絞り込み',
            'セッション数・PV数 の範囲指定',
            '該当ユーザー数と行動サマリの確認',
        ],
        metrics: ['activeUsers', 'sessions', 'screenPageViews', 'deviceCategory', 'sessionSource'],
        apiRoute: 'POST /api/user/segment-builder',
    },
    {
        name: 'コホートリテンション',
        href: '/user/cohort',
        category: 'ユーザー分析',
        description: '週別の初回訪問コホートごとに、その後の継続率をマトリクス形式で表示します。「登録後フォローメール施策の前後でDay7継続率が変わったか」などの施策評価に使います。',
        capabilities: [
            '初回訪問週ごとのコホート分類',
            'Week0〜Week8+ の継続率マトリクス',
            '期間全体の平均継続率チャート',
            '全体継続率 vs 直近コホートの比較',
            '施策マーカー（期間中のABテストを色分け表示し、施策実施中に流入したコホートをマトリクス上でマーキング）',
        ],
        metrics: ['cohortActiveUsers', 'cohortRetentionRate'],
        apiRoute: 'POST /api/user/cohort',
    },
    {
        name: '活動スコアリング',
        href: '/user/scoring',
        category: 'ユーザー分析',
        description: 'デバイス・流入元などのセグメント軸ごとに、直近性(Recency)・頻度(Frequency)・熱量(Engagement)・深度(Depth) の4軸でスコアリングし、活性 / 休眠 / 離脱リスクに分類します。',
        capabilities: [
            '6種類のセグメント軸（デバイス・流入元・流入経路・OS・ブラウザ・国）',
            '0〜100点の正規化スコア',
            '活性（70+）/ 休眠（30-69）/ 離脱リスク（0-29）の自動分類',
            'Recency / Frequency / Engagement / Depth の詳細ブレイクダウン',
            'AI によるセグメント間の差異分析と改善施策提案',
        ],
        metrics: ['activeUsers', 'sessions', 'screenPageViews', 'engagementRate'],
        ai: true,
        apiRoute: 'POST /api/user/scoring',
    },
    {
        name: 'スティッキネス分析',
        href: '/user/stickiness',
        category: 'ユーザー分析',
        description: 'DAU / WAU / MAU の推移を可視化し、DAU/MAU 比（スティッキネス）でユーザーエンゲージメントの深さを測定します。2期間比較モードで施策前後の変化を定量評価できます。',
        capabilities: [
            'DAU / WAU / MAU の日次推移グラフ',
            'DAU/MAU スティッキネス（20%以上: 高、10-20%: 中、10%未満: 低）',
            '期間比較モード（期間A vs 期間B の指標比較と変化率）',
            '相対日数での DAU / MAU オーバーレイグラフ',
            'AI によるエンゲージメント評価と改善提案',
        ],
        metrics: ['activeUsers', 'active7DayUsers', 'active28DayUsers', 'sessions'],
        ai: true,
        apiRoute: 'POST /api/user/stickiness',
    },

    // ── 経路・離脱分析 ──
    {
        name: 'ユーザー経路分析',
        href: '/journey',
        category: '経路・離脱分析',
        description: 'GA4 の pageReferrer × sessionDefaultChannelGroup を使い、訪問からフォーム到達までの遷移フローを Sankey ダイアグラムで可視化します。フォーム到達率・離脱経路パターンも集計します。',
        capabilities: [
            'Sankey ダイアグラムによる遷移フロー（チャネル → ページカテゴリ → ゴール）',
            '上位ページ遷移パターン（カテゴリ / URL パス 切り替え）',
            '離脱経路パターン（チャネル → N-2 → N-1 → 離脱）',
            'フォーム別到達率テーブル（会員登録 / 応募 / featured）',
            'デバイス・チャネルフィルター',
            'AI による離脱要因分析と改善提案',
        ],
        metrics: ['activeUsers', 'screenPageViews', 'sessionDefaultChannelGroup', 'pageReferrer'],
        ai: true,
        apiRoute: 'POST /api/journey',
    },
    {
        name: '離脱分析',
        href: '/exit',
        category: '経路・離脱分析',
        description: 'ファネル各ステップの離脱数・離脱率と、離脱率の高いページを特定します。行動シグナル（平均滞在時間・スクロール到達率）を組み合わせ、AI が離脱の質（即離脱か読了後離脱か）を判定します。',
        capabilities: [
            'ファネルステップ別の離脱数・離脱率',
            '離脱率ランキング',
            'ページ別の詳細離脱指標',
            '行動シグナル表示（平均滞在時間・スクロール到達率90%）',
            'AI による離脱の質の分析（即離脱＝第一印象の問題 / 読了後離脱＝訴求・導線の問題）と改善提案',
        ],
        metrics: ['screenPageViews', 'bounceRate', 'engagementRate', 'scrolledUsers', 'userEngagementDuration'],
        ai: true,
        apiRoute: 'POST /api/exit, POST /api/exit/gemini',
    },

    {
        name: 'ページフロー分析',
        href: '/pageflow',
        category: '経路・離脱分析',
        description: '指定したページの「直前に見ていたページ」と「直後に見たページ」を両方向で集計します。サンクスページ後の誘導効果測定（例: LP応募→クロスワーク本体への遷移率）や、任意ページの導線実態の確認に使います。',
        capabilities: [
            'ページパス前方一致での対象指定（例: /lp-thanks で全事業のLP応募サンクスをまとめて分析）',
            '経路別比較: 直前ページごとの「表示PV × 到達PV × 遷移率」（そのページを見たうち何%が対象へ進んだかの効率比較。大職種一覧14種も個別行で内訳表示）',
            '直前ページ TOP20（サイト内はパス正規化、外部流入はドメインでまとめて表示）',
            '直後ページ TOP20（対象ページをリファラーとする遷移先）',
            '対象ページ到達ユーザー数に対する構成比・リファラーなし数の表示',
            '期間切り替え（7 / 14 / 30 / 90日）',
        ],
        metrics: ['totalUsers', 'pageReferrer', 'pagePath'],
        apiRoute: 'POST /api/pageflow',
    },

    // ── コンバージョン・ファネル ──
    {
        name: 'エントリーフォームファネル',
        href: '/funnel',
        category: 'コンバージョン・ファネル',
        description: 'フォームの各ステップ（表示→入力→確認→完了）の通過率と離脱率を測定します。期間比較で施策前後の CVR 変化を定量評価できます。',
        capabilities: [
            'ステップ別ユーザー数・CVR・離脱率',
            '期間比較ファネル（A/B 期間の並列表示）',
            'ステップ間の落ち込み可視化',
            '期間比較時のチャネル別内訳（チャネルごとのセッション・CV・CVR の期間差分）',
            'AI によるファネル評価・期間比較インサイト（チャネル別変化を含む）',
        ],
        metrics: ['activeUsers', 'eventCount'],
        ai: true,
        apiRoute: 'GET /api/funnel/entry-form',
    },
    {
        name: '経路ファネルビルダー',
        href: '/funnel/path',
        category: 'コンバージョン・ファネル',
        description: 'ページ閲覧とクリックタグ（GTMラベル）を自由に組み合わせて、同一ユーザーの順序付きクローズドファネルを作成します。「トップ→検索モーダル→検索結果→求人詳細→応募」のような導線別の通過率比較に使えます。',
        capabilities: [
            'ステップをUIで自由に構築（2〜10個、ページ / クリックタグ混在可、並べ替え対応）',
            'GA4 の順序付きクローズドファネル（Data API v1alpha runFunnelReport）で同一ユーザーの通過を集計',
            'ステップ別ユーザー数・通過率・離脱数・起点比の可視化',
            'プリセット2種（王道経路 / 職種直リンク導線）とブラウザ内保存',
            '複数ファネル比較（プリセット・保存済みから2〜4個選んで通過率を横並び比較、全体通過率つき）',
            '期間切り替え（7 / 14 / 30 / 90日）',
        ],
        metrics: ['activeUsers', 'unifiedPagePathScreen', 'customEvent:click_label'],
        apiRoute: 'POST /api/funnel/path',
    },
    {
        name: 'エンゲージメントファネル',
        href: '/funnel/engagement',
        category: 'コンバージョン・ファネル',
        description: 'ページ滞在時間の長さ（10秒 / 30秒 / 60秒 / 3分以上）をファネル形式で可視化し、コンテンツへの深いエンゲージメントを測定します。',
        capabilities: [
            '滞在時間しきい値別の到達率（10s / 30s / 60s / 180s）',
            '複数ページの比較',
            'AI によるエンゲージメント傾向分析',
        ],
        metrics: ['userEngagementDuration', 'activeUsers'],
        ai: true,
        apiRoute: 'GET /api/funnel/engagement',
    },

    // ── ABテスト ──
    {
        name: 'ABテスト',
        href: '/ab-test',
        category: 'ABテスト',
        description: 'GA4 データをソースとした A/B テストの管理・実行・評価を行います。統計的有意差検定（Z検定）・サンプルサイズ・改善率の判定基準を設定し、AI が勝者の推奨を補足します。',
        capabilities: [
            'テスト作成・編集・ステータス管理（running / paused / completed）',
            'GA4フィルタ・除外フィルタ（例: pageLocation に userId= を含むイベントを除外し、LP経由ユーザーを除いた直接流入のみでCVR比較）',
            'Z検定による統計的有意差判定',
            'サンプルサイズ・テスト期間・改善率の合否チェック',
            'スケジュール実行・Webhook 通知',
            '勝者判定後の AI 評価コメント',
            'セグメント別（デバイス / チャネルなど）の内訳確認',
            '途中経過ファネルのビュー基準 / クリック基準 切り替え（ビュー計測の取りこぼしをクリック実数と比較検証できる）',
            '途中経過ファネルの「LP経由を除く」トグル（テストの除外フィルタ設定を全ステップ集計に適用し、直接流入のみのファネルを表示）',
            'テスト終了時の AI 最終レポート自動生成（結果サマリー・仮説検証・勝因敗因・学び・次のアクション。クリック基準ファネルを判断材料に含め、どのステップで差がついたかを分析）',
            '最終レポートの BigQuery 蓄積（ab_test_final_report_log）',
        ],
        ai: true,
        apiRoute: 'GET /api/ab-test, POST /api/ab-test/evaluate',
    },
    {
        name: '施策提案AI壁打ち',
        href: '/ab-test/advisor',
        category: 'ABテスト',
        description: '検討中の施策・ABテスト案を入力すると、BigQuery と DB に蓄積された過去 AB テストの勝因・敗因・最終レポートをコンテキストに、AI が成功確度・リスク・推奨テスト設計を回答します。',
        capabilities: [
            '過去 AB テスト実績（勝者・改善率・有意差・勝因敗因メモ・最終レポート）との照合',
            '類似する過去施策の提示と成功確度評価（高 / 中 / 低）',
            'リスク・落とし穴の指摘と成功確度を上げる修正案',
            '推奨テスト設計（仮説文・期待改善率・期間・評価指標）',
            '参照した過去 AB テストへのリンク表示',
        ],
        ai: true,
        apiRoute: 'POST /api/ab-test/advisor',
    },

    // ── レポート・データ ──
    {
        name: '職種別CV分析',
        href: '/occupation',
        category: 'レポート・データ',
        description: '会員登録フォームの職種パラメータ（occ）別の登録CVと職種ページ配下のセッションから、職種ごとの獲得状況を比較します。事業領域別のLP応募CV内訳も表示します。',
        capabilities: [
            '職種別の会員登録CV（サンクスページの ?occ= パラメータで分類）',
            '職種配下セッション（/{職種スラッグ} 配下ページの合計）と登録率',
            '職種行クリックでサブカテゴリ内訳を展開（例: /driver/chugata-truck 別セッション・一覧トップ・都道府県・求人詳細）',
            '事業領域別 LP応募CV（/lp-thanks/{slug} 別の内訳と構成比）',
            '期間切り替え（7 / 14 / 30 / 90日）',
            'AI 考察（伸びしろ職種・流入強化候補の特定と施策提案）',
        ],
        metrics: ['totalUsers', 'sessions', 'pagePathPlusQueryString'],
        ai: true,
        apiRoute: 'POST /api/occupation',
    },
    {
        name: 'スカウト効果ファネル',
        href: '/scout',
        category: 'レポート・データ',
        description: 'スカウトの送信リクエスト（本体DB: ScoutHistories）→ スカウトページ閲覧（GA4 /scout/）→ 応募（scoutId付きURLでの送信ボタンクリック）を一本のファネルで確認します。企業別内訳と日別推移つき。',
        capabilities: [
            '送信リクエスト・送達・閲覧UU・応募のファネルサマリー（送達はdrm-front側のSMS送信結果書き戻し実装後に表示）',
            '企業別内訳（送信リクエスト / 閲覧UU / 応募 / 閲覧→応募率）。scoutIdで企業に紐付け',
            '日別推移（送信リクエスト・閲覧・応募の3系列バー）',
            '期間切り替え（7 / 30 / 90 / 180日）',
        ],
        metrics: ['totalUsers', 'pagePath', 'pageLocation', 'customEvent:click_label'],
        apiRoute: 'POST /api/scout/funnel',
    },
    {
        name: '求人種別CV分析',
        href: '/cv-types',
        category: 'レポート・データ',
        description: '応募CVを契約種別（人材紹介 / 求人広告 / ハローワーク）に分解し、会員登録と並べて状況を確認します。drm-front の GTM ラベル規則（JobR / JobA / JobH、サンクスは ThxJob*）を利用しています。',
        capabilities: [
            '求人種別ごとの応募完了数と構成比（完了は送信ボタンクリック基準。DB実応募数との一致を確認済み・bot耐性あり）',
            '求人種別ファネル: 求人詳細閲覧 → 応募フォーム → 完了（各遷移率つき）',
            '求人詳細の流入内訳（種別×チャネル: Organic検索/Direct/CRM/広告 と 一覧経由率）。ハロワ=SEO直接着地が大半、人材紹介=Direct/CRM比重が高い等の構造を常設で確認できる',
            '応募の全体像（DB実数）: 本体DynamoDBの会員+ゲスト応募を種別×流入レイヤー（自然/featured=CRM配信/CA紹介/スカウト）で分解。GA4に乗らないfeatured経由（応募の約9割）を含む実数',
            '応募フォームの項目別ファネル: フォーム表示→各入力項目のタップ（着手）→送信を種別別に表示。どの項目で手が止まるかを特定（2026-07-28以降のデータ・ゲスト応募の行動）',
            '経路別ファネル（種別×経路）: GA4クローズドファネルで 一覧→詳細→フォーム→完了 を人材紹介/求人広告/ハローワーク×一覧経由/直接着地の6行に分解。ハロワは一覧経由2.3% vs 直接着地0.4%など、経路による応募力の差を常設表示',
            '会員登録の内訳: 登録のみ（GA4 thanks到達）と応募と同時の登録（応募時刻とユーザー作成時刻の近接判定・種別つき）を分解',
            '会員登録のフォーム→完了を参考行として併記',
            '完了数の日別推移チャート（4系列）',
            '期間切り替え（7 / 14 / 30 / 90日）',
        ],
        metrics: ['totalUsers', 'customEvent:view_label', 'pagePath'],
        apiRoute: 'POST /api/cv-types',
    },
    {
        name: '月次インサイトレポート',
        href: '/insights',
        category: 'レポート・データ',
        description: '今月と先月の主要 KPI（アクティブユーザー・セッション・エンゲージメント率・PV など）を自動集計し、AI がサマリー・改善点・来月の推奨アクションを生成します。',
        capabilities: [
            '今月 vs 先月の KPI 比較テーブル（前月比%付き）',
            '今月の上位ページ（PV順）',
            'AI による月次インサイトレポート生成（サマリー / 良い点 / 注意点 / 推奨アクション）',
        ],
        metrics: ['activeUsers', 'newUsers', 'sessions', 'engagementRate', 'averageSessionDuration', 'screenPageViews'],
        ai: true,
        apiRoute: 'POST /api/insights',
    },
    {
        name: 'トレンド分析',
        href: '/trend',
        category: 'レポート・データ',
        description: '月次・週次の PV / CV / CVR 推移をレポートテンプレートごとに集計します。AI が月による傾向・落ち込み期間・改善期間を分析します。',
        capabilities: [
            '月次 CVR トレンドグラフ',
            '週次内訳での詳細推移',
            'AI による月別傾向分析（落ち込み月・好調月の特定）',
        ],
        metrics: ['sessions', 'eventCount', 'cvr'],
        ai: true,
        apiRoute: 'GET /api/trend/monthly',
    },
    {
        name: 'GA4分析',
        href: '/analytics',
        category: 'レポート・データ',
        description: 'GA4 のデータをレポートテンプレートに基づいて集計します。セッション・PV・CVR・エンゲージメント率・直帰率などを表示します。',
        capabilities: [
            'テンプレート別のGA4レポート集計',
            'A/B テストとのデータ連動',
            'エクスポート対応',
        ],
        apiRoute: 'GET /api/analytics/report',
    },
    {
        name: 'ヒートマップ',
        href: '/heatmap',
        category: 'レポート・データ',
        description: 'GTM 経由で収集したクリック座標・スクロール深度をヒートマップとして可視化します。ページのどの要素が注目されているかを視覚的に把握できます。',
        capabilities: [
            'クリックヒートマップ（座標密度表示）',
            'スクロール深度マップ',
            'ビュー別ラベル管理',
        ],
        apiRoute: 'GET /api/heatmap/view-labels',
    },
    {
        name: '週次AIサマリー配信',
        category: 'レポート・データ',
        description: '毎週月曜 09:00 JST に先週（月〜日）の主要KPI・チャネル別セッション変動・実行中ABテストの途中経過を集計し、AIサマリー（ハイライト・気になる変化・今週のアクション）を添えて Slack に自動配信します。UIページはなくスケジューラが自動実行します。',
        capabilities: [
            '先週 vs 前週の KPI 比較（セッション・新規ユーザー・応募CV・LP応募CV・会員登録CV・全体CVR）',
            'チャネル別セッションの変動上位（前週比）',
            '実行中 AB テストの途中経過（バリアント別CVR・有意差）',
            'AI サマリー（先週のハイライト / 気になる変化 / 今週のアクション）',
        ],
        metrics: ['sessions', 'newUsers', 'totalUsers', 'sessionDefaultChannelGroup'],
        ai: true,
        apiRoute: 'POST /api/reports/weekly-summary',
    },
    {
        name: 'CV急落アラート',
        href: '/alerts',
        category: 'レポート・データ',
        description: '毎日 09:30 JST に前日のセッション数・応募CV・LP応募CV・会員登録CV・全体CVR をチェックし、過去8週の同一曜日の中央値からしきい値（デフォルト30%）以上下落した指標があれば Slack に通知します。チェックはスケジューラが自動実行し、しきい値や監視対象は設定画面から変更できます。',
        capabilities: [
            '曜日変動対策（過去8週の同一曜日と比較）・スパイク対策（平均でなく中央値）',
            '対象指標: セッション数 / 応募CV / LP応募CV / 会員登録CV / 全体CVR',
            'しきい値未満のノイズ除去（ベースラインが小さすぎる指標は判定しない）',
            '発火時の原因ドリルダウン（チャネル別・デバイス別・ページ別の下落幅内訳を自動集計）',
            'AI 原因仮説（内訳データと整合する原因候補と確認ポイントを生成）',
            'Slack 通知（下落指標・下落率・内訳・AI仮説）',
            'プロダクト別設定画面（有効/無効・下落しきい値・最小ベースライン・監視対象指標）',
        ],
        metrics: ['sessions', 'totalUsers', 'sessionDefaultChannelGroup', 'deviceCategory'],
        ai: true,
        apiRoute: 'POST /api/alerts/cv-drop',
    },
]
