export interface FeatureDoc {
    name: string
    /** UIページがない機能（バックグラウンド実行のみ）は省略 */
    href?: string
    category: string
    description: string
    capabilities: string[]
    metrics?: string[]
    ai?: boolean
    apiRoute?: string
}

export const FEATURE_CATEGORIES = [
    'KPI・レポート',
    'CV分析',
    'チャネル・集客',
    'ABテスト',
    'コンバージョン・ファネル',
    '可視化・経路分析',
    'ユーザー分析',
    'データ・ツール',
] as const

export const FEATURE_LIST: FeatureDoc[] = [
    // ── ユーザー分析 ──
    {
        name: 'CVセッション解剖（BQ）',
        href: '/user/flow',
        category: 'ユーザー分析',
        description: 'BigQueryのGA4生イベント（x-work-ga.analytics_534098180.events_*、2026-08-07〜）をセッション単位でSQL集計。応募・登録した人が「何件の求人詳細を見て・検索を使って・何分で」CVしたかを非CVセッションと比較し、求人詳細ページ直後の遷移先（次アクション）の実測割合を表示します。GA4 APIの集計値では不可能なセッション内行動の分解が目的。',
        capabilities: [
            'グループ別行動量比較（応募あり / 会員登録あり / 非CV求人閲覧あり / 非CV閲覧なし）: 求人詳細閲覧数の平均・中央値、検索利用率、滞在時間、CVまでの所要時間',
            '求人詳細の閲覧数分布（0 / 1 / 2〜3 / 4〜9 / 10件以上）— 応募ありの0件は一覧モーダル・featured等の非詳細導線',
            '求人詳細→次アクション内訳（別の詳細 / 検索 / 一覧 / 応募フォーム / 離脱 等）— 詳細→フォーム進出率がFV改善・CTA施策のKPI',
            '応募 = EF__Job(R|A|H)__Btnクリック（実応募一致）、登録 = /members/signup/thanks到達、検索 = /search・一覧・資格条件',
            'クエリは毎回dry runでスキャン量を確認（5GB超で中止）。7日間で約660MB・1円未満',
        ],
        metrics: ['event_name', 'page_location', 'click_label', 'ga_session_id'],
        apiRoute: 'POST /api/user-flow',
    },
    {
        name: 'ユーザー行動タイムライン',
        href: '/user',
        category: 'ユーザー分析',
        description: 'user_pseudo_id を指定すると、そのユーザーが「いつ・どのページを見て・何を操作したか」を時系列で表示します。施策後の個別確認や CS 対応に活用できます。',
        capabilities: [
            'user_pseudo_id によるユーザー絞り込み',
            '日付グループ別イベントタイムライン',
            'ページビュー・クリック・セッション開始などのイベント種別表示',
            'ページタイトル・パラメータの確認',
        ],
        metrics: ['activeUsers', 'eventName', 'pagePath', 'pageTitle'],
        apiRoute: 'POST /api/user/timeline',
    },
    {
        name: 'ユーザーリスト・セグメントビルダー',
        href: '/user/segment-builder',
        category: 'ユーザー分析',
        description: 'デバイス・流入元・PV数などの条件を組み合わせてユーザーをフィルタリングし、該当ユーザー数と行動傾向を確認します。CRM 連携やリターゲティング施策の対象絞り込みに使います。',
        capabilities: [
            '複数条件の AND 絞り込み',
            'デバイス / OS / ブラウザ / 流入元 / 国 での絞り込み',
            'セッション数・PV数 の範囲指定',
            '該当ユーザー数と行動サマリの確認',
        ],
        metrics: ['activeUsers', 'sessions', 'screenPageViews', 'deviceCategory', 'sessionSource'],
        apiRoute: 'POST /api/user/segment-builder',
    },
    {
        name: 'コホートリテンション',
        href: '/user/cohort',
        category: 'ユーザー分析',
        description: '週別の初回訪問コホートごとに、その後の継続率をマトリクス形式で表示します。「登録後フォローメール施策の前後でDay7継続率が変わったか」などの施策評価に使います。',
        capabilities: [
            '初回訪問週ごとのコホート分類',
            'Week0〜Week8+ の継続率マトリクス',
            '期間全体の平均継続率チャート',
            '全体継続率 vs 直近コホートの比較',
            '施策マーカー（期間中のABテストを色分け表示し、施策実施中に流入したコホートをマトリクス上でマーキング）',
        ],
        metrics: ['cohortActiveUsers', 'cohortRetentionRate'],
        apiRoute: 'POST /api/user/cohort',
    },
    {
        name: '活動スコアリング',
        href: '/user/scoring',
        category: 'ユーザー分析',
        description: 'デバイス・流入元などのセグメント軸ごとに、直近性(Recency)・頻度(Frequency)・熱量(Engagement)・深度(Depth) の4軸でスコアリングし、活性 / 休眠 / 離脱リスクに分類します。',
        capabilities: [
            '6種類のセグメント軸（デバイス・流入元・流入経路・OS・ブラウザ・国）',
            '0〜100点の正規化スコア',
            '活性（70+）/ 休眠（30-69）/ 離脱リスク（0-29）の自動分類',
            'Recency / Frequency / Engagement / Depth の詳細ブレイクダウン',
            'AI によるセグメント間の差異分析と改善施策提案',
        ],
        metrics: ['activeUsers', 'sessions', 'screenPageViews', 'engagementRate'],
        ai: true,
        apiRoute: 'POST /api/user/scoring',
    },
    {
        name: 'スティッキネス分析',
        href: '/user/stickiness',
        category: 'ユーザー分析',
        description: 'DAU / WAU / MAU の推移を可視化し、DAU/MAU 比（スティッキネス）でユーザーエンゲージメントの深さを測定します。2期間比較モードで施策前後の変化を定量評価できます。',
        capabilities: [
            'DAU / WAU / MAU の日次推移グラフ',
            'DAU/MAU スティッキネス（20%以上: 高、10-20%: 中、10%未満: 低）',
            '期間比較モード（期間A vs 期間B の指標比較と変化率）',
            '相対日数での DAU / MAU オーバーレイグラフ',
            'AI によるエンゲージメント評価と改善提案',
        ],
        metrics: ['activeUsers', 'active7DayUsers', 'active28DayUsers', 'sessions'],
        ai: true,
        apiRoute: 'POST /api/user/stickiness',
    },

    // ── 経路・離脱分析 ──
    {
        name: 'ユーザー経路分析',
        href: '/journey',
        category: '可視化・経路分析',
        description: 'GA4 の pageReferrer × sessionDefaultChannelGroup を使い、訪問からフォーム到達までの遷移フローを Sankey ダイアグラムで可視化します。フォーム到達率・離脱経路パターンも集計します。',
        capabilities: [
            'Sankey ダイアグラムによる遷移フロー（チャネル → ページカテゴリ → ゴール）',
            '上位ページ遷移パターン（カテゴリ / URL パス 切り替え）',
            '離脱経路パターン（チャネル → N-2 → N-1 → 離脱）',
            'フォーム別到達率テーブル（会員登録 / 応募 / featured）',
            'デバイス・チャネルフィルター',
            'AI による離脱要因分析と改善提案',
        ],
        metrics: ['activeUsers', 'screenPageViews', 'sessionDefaultChannelGroup', 'pageReferrer'],
        ai: true,
        apiRoute: 'POST /api/journey',
    },
    {
        name: '離脱分析',
        href: '/exit',
        category: '可視化・経路分析',
        description: 'ファネル各ステップの離脱数・離脱率と、離脱率の高いページを特定します。行動シグナル（平均滞在時間・スクロール到達率）を組み合わせ、AI が離脱の質（即離脱か読了後離脱か）を判定します。',
        capabilities: [
            'ファネルステップ別の離脱数・離脱率',
            '離脱率ランキング',
            'ページ別の詳細離脱指標',
            '行動シグナル表示（平均滞在時間・スクロール到達率90%）',
            'AI による離脱の質の分析（即離脱＝第一印象の問題 / 読了後離脱＝訴求・導線の問題）と改善提案',
        ],
        metrics: ['screenPageViews', 'bounceRate', 'engagementRate', 'scrolledUsers', 'userEngagementDuration'],
        ai: true,
        apiRoute: 'POST /api/exit, POST /api/exit/gemini',
    },

    {
        name: 'ページフロー分析',
        href: '/pageflow',
        category: '可視化・経路分析',
        description: '指定したページの「直前に見ていたページ」と「直後に見たページ」を両方向で集計します。サンクスページ後の誘導効果測定（例: LP応募→クロスワーク本体への遷移率）や、任意ページの導線実態の確認に使います。',
        capabilities: [
            'ページパス前方一致での対象指定（例: /lp-thanks で全事業のLP応募サンクスをまとめて分析）',
            '経路別比較: 直前ページごとの「表示PV × 到達PV × 遷移率」（そのページを見たうち何%が対象へ進んだかの効率比較。大職種一覧14種も個別行で内訳表示）',
            '直前ページ TOP20（サイト内はパス正規化、外部流入はドメインでまとめて表示）',
            '直後ページ TOP20（対象ページをリファラーとする遷移先）',
            '対象ページ到達ユーザー数に対する構成比・リファラーなし数の表示',
            '期間切り替え（7 / 14 / 30 / 90日）',
        ],
        metrics: ['totalUsers', 'pageReferrer', 'pagePath'],
        apiRoute: 'POST /api/pageflow',
    },

    // ── コンバージョン・ファネル ──
    {
        name: '会員登録フォームファネル',
        href: '/signup-funnel',
        category: 'コンバージョン・ファネル',
        description: '会員登録フォーム（職種選択→各質問→登録完了）の質問別通過状況を view（画面を見た人）と click（回答して進んだ人）の両方で常設表示します。期間内に実際に発火した SU__ ラベルから質問構造を自動復元するため、ABテストのサフィックス（__B-xxxx）やステップ番号の振り直し・質問文変更があってもコード変更なしで追従します。',
        capabilities: [
            '職種フォーム別のタブ切り替え（Driver / Soko など、期間内にデータがあるフォームを自動検出）',
            '質問ごとの view / click / 起点比 / ステップ離脱率（職種選択クリック起点）',
            'ABテスト変種を質問文ベースで自動統合（変種間でステップ番号がズレていても正しく合算）',
            '離脱率の色分け（15%以上=赤 / 10%以上=黄）と残存バー',
            '完走率サマリー（職種選択→登録完了）',
            '期間切り替え（7 / 14 / 30 / 90日・今月・前月・カスタム日付指定）',
            '職種別×全体の推移チャート（流入=職種選択クリック / 登録完了=thanks到達を?occ=で職種分解 / 完走率の3指標切替、35日超は週次集約）と職種別合計テーブル',
            '前期間比較（直前の同じ長さの期間）: 全体サマリーカードと職種別テーブルに流入・完了の変化率（%）と完走率のポイント差（pt）を色付き表示',
        ],
        metrics: ['totalUsers', 'customEvent:view_label', 'customEvent:click_label', 'pagePathPlusQueryString'],
        apiRoute: 'POST /api/signup-funnel（推移は POST /api/signup-funnel/trend）',
    },
    {
        name: 'エントリーフォームファネル',
        href: '/funnel',
        category: 'コンバージョン・ファネル',
        description: 'フォームの各ステップ（表示→入力→確認→完了）の通過率と離脱率を測定します。期間比較で施策前後の CVR 変化を定量評価できます。',
        capabilities: [
            'ステップ別ユーザー数・CVR・離脱率',
            '期間比較ファネル（A/B 期間の並列表示）',
            'ステップ間の落ち込み可視化',
            '期間比較時のチャネル別内訳（チャネルごとのセッション・CV・CVR の期間差分）',
            'AI によるファネル評価・期間比較インサイト（チャネル別変化を含む）',
        ],
        metrics: ['activeUsers', 'eventCount'],
        ai: true,
        apiRoute: 'GET /api/funnel/entry-form',
    },
    {
        name: '経路ファネルビルダー',
        href: '/funnel/path',
        category: 'コンバージョン・ファネル',
        description: 'ページ閲覧とクリックタグ（GTMラベル）を自由に組み合わせて、同一ユーザーの順序付きクローズドファネルを作成します。「トップ→検索モーダル→検索結果→求人詳細→応募」のような導線別の通過率比較に使えます。',
        capabilities: [
            'ステップをUIで自由に構築（2〜10個、ページ / クリックタグ混在可、並べ替え対応）',
            'GA4 の順序付きクローズドファネル（Data API v1alpha runFunnelReport）で同一ユーザーの通過を集計',
            'ステップ別ユーザー数・通過率・離脱数・起点比の可視化',
            'プリセット2種（王道経路 / 職種直リンク導線）とブラウザ内保存',
            '複数ファネル比較（プリセット・保存済みから2〜4個選んで通過率を横並び比較、全体通過率つき）',
            '期間切り替え（7 / 14 / 30 / 90日）',
        ],
        metrics: ['activeUsers', 'unifiedPagePathScreen', 'customEvent:click_label'],
        apiRoute: 'POST /api/funnel/path',
    },
    {
        name: 'エンゲージメントファネル',
        href: '/funnel/engagement',
        category: 'コンバージョン・ファネル',
        description: 'ページ滞在時間の長さ（10秒 / 30秒 / 60秒 / 3分以上）をファネル形式で可視化し、コンテンツへの深いエンゲージメントを測定します。',
        capabilities: [
            '滞在時間しきい値別の到達率（10s / 30s / 60s / 180s）',
            '複数ページの比較',
            'AI によるエンゲージメント傾向分析',
        ],
        metrics: ['userEngagementDuration', 'activeUsers'],
        ai: true,
        apiRoute: 'GET /api/funnel/engagement',
    },

    // ── ABテスト ──
    {
        name: 'ABテスト',
        href: '/ab-test',
        category: 'ABテスト',
        description: 'GA4 データをソースとした A/B テストの管理・実行・評価を行います。統計的有意差検定（Z検定）・サンプルサイズ・改善率の判定基準を設定し、AI が勝者の推奨を補足します。',
        capabilities: [
            'テスト作成・編集・ステータス管理（running / paused / completed）',
            'GA4フィルタ・除外フィルタ（例: pageLocation に userId= を含むイベントを除外し、LP経由ユーザーを除いた直接流入のみでCVR比較）',
            'Z検定による統計的有意差判定',
            'サンプルサイズ・テスト期間・改善率の合否チェック',
            'スケジュール実行・Webhook 通知',
            '勝者判定後の AI 評価コメント',
            'セグメント別（デバイス / チャネルなど）の内訳確認',
            '途中経過ファネルのビュー基準 / クリック基準 切り替え（ビュー計測の取りこぼしをクリック実数と比較検証できる）',
            '途中経過ファネルの「LP経由を除く」トグル（テストの除外フィルタ設定を全ステップ集計に適用し、直接流入のみのファネルを表示）',
            'テスト終了時の AI 最終レポート自動生成（結果サマリー・仮説検証・勝因敗因・学び・次のアクション。クリック基準ファネルを判断材料に含め、どのステップで差がついたかを分析）',
            '最終レポートの BigQuery 蓄積（ab_test_final_report_log）',
        ],
        ai: true,
        apiRoute: 'GET /api/ab-test, POST /api/ab-test/evaluate',
    },
    {
        name: '施策提案AI壁打ち',
        href: '/ab-test/advisor',
        category: 'ABテスト',
        description: '検討中の施策・ABテスト案を入力すると、過去 AB テストの勝因・敗因に加えて事業の実測データ（CV単価・直近30日のファネル/チャネル/主要面の規模）をコンテキストに、AI が成功確度・金額換算インパクト・推奨テスト設計を回答します。',
        capabilities: [
            '過去 AB テスト実績（勝者・改善率・有意差・勝因敗因メモ・最終レポート）との照合',
            '類似する過去施策の提示と成功確度評価（高 / 中 / 低）',
            '事業コンテキスト注入: CV単価係数（cvUnitValue.ts）＋GA4直近30日実測（種別ファネル・会員登録・一覧UU・チャネル構成）を毎回自動取得してプロンプトに同梱（GA4障害時は単価のみで続行）',
            '想定インパクトの金額換算（対象規模×リフトシナリオ×CV単価で「+◯万円/月」を提示、不明数値は捏造せず要実測と明示）',
            'リスク・落とし穴の指摘と成功確度を上げる修正案',
            '推奨テスト設計（仮説文・主要KPI・期間・検出力の概算式つき）',
            '参照した過去 AB テストへのリンク表示',
        ],
        ai: true,
        apiRoute: 'POST /api/ab-test/advisor',
    },

    // ── レポート・データ ──
    {
        name: '職種別CV分析',
        href: '/occupation',
        category: 'CV分析',
        description: '会員登録フォームの職種パラメータ（occ）別の登録CVと職種ページ配下のセッションから、職種ごとの獲得状況を比較します。事業領域別のLP応募CV内訳も表示します。',
        capabilities: [
            '職種別の会員登録CV（サンクスページの ?occ= パラメータで分類）',
            '職種配下セッション（/{職種スラッグ} 配下ページの合計）と登録率',
            '職種行クリックでサブカテゴリ内訳を展開（例: /driver/chugata-truck 別セッション・一覧トップ・都道府県・求人詳細）',
            '事業領域別 LP応募CV（/lp-thanks/{slug} 別の内訳と構成比）',
            '期間切り替え（7 / 14 / 30 / 90日）',
            'AI 考察（伸びしろ職種・流入強化候補の特定と施策提案）',
        ],
        metrics: ['totalUsers', 'sessions', 'pagePathPlusQueryString'],
        ai: true,
        apiRoute: 'POST /api/occupation',
    },
    {
        name: 'スカウト効果ファネル',
        href: '/scout',
        category: 'コンバージョン・ファネル',
        description: 'スカウトの送信リクエスト（本体DB: ScoutHistories）→ スカウトページ閲覧（GA4 /scout/）→ 応募（scoutId付きURLでの送信ボタンクリック）を一本のファネルで確認します。企業別内訳と日別推移つき。',
        capabilities: [
            '送信リクエスト・送達・閲覧UU・応募のファネルサマリー（送達はdrm-front側のSMS送信結果書き戻し実装後に表示）',
            '企業別内訳（送信リクエスト / 閲覧UU / 応募 / 閲覧→応募率）。scoutIdで企業に紐付け',
            '日別推移（送信リクエスト・閲覧・応募の3系列バー）',
            '期間切り替え（7 / 30 / 90 / 180日）',
        ],
        metrics: ['totalUsers', 'pagePath', 'pageLocation', 'customEvent:click_label'],
        apiRoute: 'POST /api/scout/funnel',
    },
    {
        name: '求人種別CV分析',
        href: '/cv-types',
        category: 'CV分析',
        description: '応募CVを契約種別（人材紹介 / 求人広告 / ハローワーク）に分解し、会員登録と並べて状況を確認します。drm-front の GTM ラベル規則（JobR / JobA / JobH、サンクスは ThxJob*）を利用しています。',
        capabilities: [
            '求人種別ごとの応募完了数と構成比（完了は送信ボタンクリック基準。DB実応募数との一致を確認済み・bot耐性あり）',
            'CVの期待売上換算（円）: 応募・会員登録1件あたりの期待売上係数（Salesforce入社済受注額−返金から算出。人材紹介約5,300円・求人広告約7,800円・ハロワ約2,800円/応募、会員登録約1.8万円/登録）でサマリーカードに金額表示。施策の価値比較用（lib/constants/cvUnitValue.ts）',
            '求人種別ファネル: 求人詳細閲覧 → 応募フォーム → 完了（各遷移率つき）',
            'サイト全体の流入チャネル構成比（セッション基準・構成比バーつき）。ラストタッチ基準のためオーガニックの価値は構成比より重い旨の注記つき',
            '求人詳細の流入内訳（種別×チャネル: Organic検索/Direct/CRM/広告 と 一覧経由率）。ハロワ=SEO直接着地が大半、人材紹介=Direct/CRM比重が高い等の構造を常設で確認できる',
            '応募の全体像（DB実数）: 本体DynamoDBの会員+ゲスト応募を種別×流入レイヤー（自然/featured=CRM配信/CA紹介/スカウト）で分解。GA4に乗らないfeatured経由（応募の約9割）を含む実数',
            '応募フォームの項目別ファネル: フォーム表示→各入力項目のタップ（着手）→送信を種別別に表示。どの項目で手が止まるかを特定（2026-07-28以降のデータ・ゲスト応募の行動）',
            '経路別ファネル（種別×経路）: GA4クローズドファネルで 一覧→詳細→フォーム→完了 を人材紹介/求人広告/ハローワーク×一覧経由/直接着地の6行に分解。ハロワは一覧経由2.3% vs 直接着地0.4%など、経路による応募力の差を常設表示',
            '会員登録の内訳: 登録のみ（GA4 thanks到達）と応募と同時の登録（応募時刻とユーザー作成時刻の近接判定・種別つき）を分解',
            '会員登録のフォーム→完了を参考行として併記',
            '完了数の日別推移チャート（4系列）',
            '期間切り替え（7 / 14 / 30 / 90日）',
        ],
        metrics: ['totalUsers', 'customEvent:view_label', 'pagePath'],
        apiRoute: 'POST /api/cv-types',
    },
    {
        name: 'CV単価・お金まわり',
        href: '/cv-value',
        category: 'KPI・レポート',
        description: '応募・会員登録1件あたりの期待売上（CV単価）と、期間のCV数を金額換算した早見ページ。施策の価値比較・優先度判断の共通モノサシとして使います。係数はSalesforce実測（登録履歴→求職者→マッチング入社済の受注額−返金想定）から算出。',
        capabilities: [
            'CV単価カード: 会員登録（単独）約1.8万円・人材紹介応募 約5,300円・求人広告応募 約7,800円・ハローワーク応募 約2,800円。相互の倍率つき（例: 登録1件=ハロワ応募6.5件分）',
            '期間のCVを金額換算: DB実数ベース（featured/CRM配信込み・実態）とGA4サイト内フォームベース（施策試算用）の2表',
            '単価の算出根拠テーブル: コホート期間・CV件数・入社成約数・成約率・受注額−返金・備考（求人広告は紹介パスアップ分のみ等）を常設表示',
            '係数は lib/constants/cvUnitValue.ts で一元管理（四半期に1回程度の再算出を推奨。手順はメモリ project_cv_unit_value.md / ファイルコメント参照）',
        ],
        metrics: ['totalUsers', 'customEvent:click_label'],
        apiRoute: 'POST /api/cv-types, POST /api/applications/actual（既存APIを再利用）',
    },
    {
        name: 'LINE配信レポート',
        href: '/line-report',
        category: 'チャネル・集客',
        description: 'LINE経由（utm_medium=line）の再訪・CV・期待売上換算と、おすすめ求人LINE配信（毎週火曜・連携者向けFlexカルーセル）の週次実績を常設表示。LINE施策（配信頻度AB・連携率改善等）の判定基盤。',
        capabilities: [
            'LINE経由の再訪ユーザー・セッション・CV（応募/LP応募/会員登録）と円換算（CV単価係数）',
            'utm_source別内訳（product=週次おすすめ配信 / ca / scout 等）',
            '週次配信実績（BQ xmile-drm.xwork.line_job_recommendation_unit_stats）: 連携者数の推移・配信成功・受取拒否率・求人マッチなし。※write SAにxmile-drmの閲覧権限が必要（未付与時は付与手順を画面に表示）',
            '日別再訪の簡易バーチャート（火曜配信ピークの確認・配信頻度ABの健全性監視用）',
            'クリック統計（LINE Insight）はdrm-front側でBQ未連携のため未対応（連携後に追加予定）',
        ],
        metrics: ['sessions', 'activeUsers', 'sessionSource', 'sessionMedium'],
        apiRoute: 'POST /api/line-report',
    },
    {
        name: 'SEOモニタ',
        href: '/seo-report',
        category: 'チャネル・集客',
        description: 'Search Console（sc-domain:x-work.jp）の掲載順位・表示回数・CTR・クリックをページカテゴリ別に常時監視。施策（モザイク・モーダル・FV変更等）のSEO影響を「対象カテゴリ vs 非対象カテゴリの前後比較（DiD）」で判定するための基盤。',
        capabilities: [
            '全体サマリー（クリック・表示回数・CTR・平均順位）と前期間比',
            'ページカテゴリ別（求人詳細/検索・一覧/資格条件/TOP/コラム）の前期間比較。施策を当てたカテゴリだけ悪化→施策影響、全カテゴリ一斉変動→アルゴリズム更新、の切り分けができる',
            '日別推移（クリックバー・表示回数・平均順位）と上位検索クエリ',
            'URL別表示: 上位20ページの前期間比つきテーブル＋パス正規表現フィルタ（例: /(driver)/media_.*）。フィルタ適用でサマリー・日別・クエリ・URL表すべてが対象URL群に絞られる',
            '検索タイプ別トレンド: Googleしごと検索枠（JOB_LISTING/JOB_DETAILS、クリックの約3割）の前期間比を常設表示。JobPosting構造化データの健全性監視用',
            'SEOカテゴリ急落の常設アラート: 毎日10:00にカテゴリ別クリックの前週比を判定（-25%超かつ前週200クリック以上で🚨即時Slack通知）、毎週月曜は全カテゴリの週次サマリーを配信。ABテストSEO監視と同じジョブで実行',
            'ABテストSEO監視（自動）: ABテスト設定の「SEO監視対象パス」に正規表現を入れると、テスト期間中毎日10:00に対象ページのGSC実績をサイト全体と対照比較（DiD、テスト開始前7日vs直近7日）。対照比クリック-20pt超 or 順位+1.0超悪化でSlack即日通知＋Gemini見立てコメント、毎週月曜は異常なしでもサマリー配信（POST /api/alerts/seo-watch）',
            'GSCデータの2〜3日ラグを考慮した期間設計（終端は3日前）。SEO反映は2〜6週かかる旨の注意書きつき',
            'SA（ai-product-dashboard@hrs-div）をSearch Consoleにユーザー追加して接続（2026-08-12設定）',
        ],
        metrics: ['clicks', 'impressions', 'ctr', 'position'],
        apiRoute: 'POST /api/seo-report',
    },
    {
        name: '月次インサイトレポート',
        href: '/insights',
        category: 'KPI・レポート',
        description: '今月と先月の主要 KPI（アクティブユーザー・セッション・エンゲージメント率・PV など）を自動集計し、AI がサマリー・改善点・来月の推奨アクションを生成します。',
        capabilities: [
            '今月 vs 先月の KPI 比較テーブル（前月比%付き）',
            '今月の上位ページ（PV順）',
            'AI による月次インサイトレポート生成（サマリー / 良い点 / 注意点 / 推奨アクション）',
        ],
        metrics: ['activeUsers', 'newUsers', 'sessions', 'engagementRate', 'averageSessionDuration', 'screenPageViews'],
        ai: true,
        apiRoute: 'POST /api/insights',
    },
    {
        name: 'トレンド分析',
        href: '/trend',
        category: 'KPI・レポート',
        description: '月次・週次の PV / CV / CVR 推移をレポートテンプレートごとに集計します。AI が月による傾向・落ち込み期間・改善期間を分析します。',
        capabilities: [
            '月次 CVR トレンドグラフ',
            '週次内訳での詳細推移',
            'AI による月別傾向分析（落ち込み月・好調月の特定）',
        ],
        metrics: ['sessions', 'eventCount', 'cvr'],
        ai: true,
        apiRoute: 'GET /api/trend/monthly',
    },
    {
        name: 'GA4分析',
        href: '/analytics',
        category: 'データ・ツール',
        description: 'GA4 のデータをレポートテンプレートに基づいて集計します。セッション・PV・CVR・エンゲージメント率・直帰率などを表示します。',
        capabilities: [
            'テンプレート別のGA4レポート集計',
            'A/B テストとのデータ連動',
            'エクスポート対応',
        ],
        apiRoute: 'GET /api/analytics/report',
    },
    {
        name: 'ヒートマップ',
        href: '/heatmap',
        category: '可視化・経路分析',
        description: 'GTM 経由で収集したクリック座標・スクロール深度をヒートマップとして可視化します。ページのどの要素が注目されているかを視覚的に把握できます。',
        capabilities: [
            'クリックヒートマップ（座標密度表示）',
            'スクロール深度マップ',
            'ビュー別ラベル管理',
        ],
        apiRoute: 'GET /api/heatmap/view-labels',
    },
    {
        name: '週次AIサマリー配信',
        category: 'KPI・レポート',
        description: '毎週月曜 09:00 JST に先週（月〜日）の主要KPI・チャネル別セッション変動・実行中ABテストの途中経過を集計し、AIサマリー（ハイライト・気になる変化・今週のアクション）を添えて Slack に自動配信します。UIページはなくスケジューラが自動実行します。',
        capabilities: [
            '先週 vs 前週の KPI 比較（セッション・新規ユーザー・応募CV・LP応募CV・会員登録CV・全体CVR）',
            'チャネル別セッションの変動上位（前週比）',
            '実行中 AB テストの途中経過（バリアント別CVR・有意差）',
            'AI サマリー（先週のハイライト / 気になる変化 / 今週のアクション）',
        ],
        metrics: ['sessions', 'newUsers', 'totalUsers', 'sessionDefaultChannelGroup'],
        ai: true,
        apiRoute: 'POST /api/reports/weekly-summary',
    },
    {
        name: 'CV急落・セグメント変動アラート',
        href: '/alerts',
        category: 'KPI・レポート',
        description: '毎日 09:30 JST に前日の指標を過去8週の同一曜日の中央値と比較してSlack通知します。全体指標（セッション・CV・CVR）の急落に加え、セグメント別（ページカテゴリ別の閲覧、CV種別×チャネル別）は急増（スパイク）も検知します。SEO順位変動・キャンペーン・bot流入・タグ事故は全体値に埋もれてセグメント単位で先に現れるため。',
        capabilities: [
            '曜日変動対策（過去8週の同一曜日と比較）・スパイク対策（平均でなく中央値）',
            '全体指標の急落検知: セッション数 / 応募CV / LP応募CV / 会員登録CV / 全体CVR（しきい値デフォルト-30%）',
            'ページカテゴリ別の急増・急落検知: 求人詳細 / 検索・一覧 / TOP / コラム / 会員登録フォーム / 応募フォーム の閲覧ユーザー（急増はデフォルト+50%、CV_SPIKE_ALERT_THRESHOLDで変更可）。発火時は変動に効いた個別ページ上位5件を添付',
            'CV種別×チャネル別の急増・急落検知: 応募CV/LP応募CV/会員登録CV × sessionDefaultChannelGroup（例: 会員登録CV×Organic Searchの急増）',
            'しきい値未満のノイズ除去（ベースラインが小さすぎるセグメントは判定しない。急増側はベースラインほぼ0からの出現も拾う）',
            '統計ガード: %しきい値に加えて中央値からポアソン3σ以上の乖離を必須化。中央値が小さい指標・セグメントが日次ゆらぎ（±√n）で発火し続けるのを防ぐ（バックテスト実測で誤報75%削減: 2.8件/日→0.7件/日。全体指標側にも適用、CVRは期待CV数との乖離で判定）',
            '発火時の原因ドリルダウン（チャネル別・デバイス別・ページ別の下落幅内訳を自動集計）',
            'AI 原因仮説（内訳データと整合する原因候補と確認ポイントを生成）',
            'Slack 通知（📊セグメント変動は急増/急落をまとめて1メッセージ、🚨全体CV急落は従来どおり）',
            'プロダクト別設定画面（有効/無効・下落しきい値・最小ベースライン・監視対象の指標/セグメントのトグル）',
        ],
        metrics: ['sessions', 'totalUsers', 'sessionDefaultChannelGroup', 'deviceCategory'],
        ai: true,
        apiRoute: 'POST /api/alerts/cv-drop',
    },
]
