/**
 * 【自動生成】scripts/check/gen-api-list.ts が app/api/**\/route.ts から生成。手で編集しない。
 * 名前・パラメータ・カテゴリの注釈は lib/docs/apiAnnotations.ts に書く。
 */

export interface GeneratedEndpoint {
    path: string
    method: string
    /** route の JSDoc 1 段落目 */
    doc: string
    file: string
}

export const GENERATED_ENDPOINTS: GeneratedEndpoint[] = [
    { path: "/api/ab-test", method: "DELETE", doc: "ABテスト一覧を取得（ページネーション対応: デフォルト5件/ページ） / export async function GET(request: Request) { try { const { searchParams } = new URL(request.url) const productId = searchParams.get('productId') const status = searchParams.get('status') const pageParam = searchParams.get('page') const limitParam = searchParams.get('limit') const page = Math.max(1, parseInt(pageParam || '1', 10) || 1) const limit = Math.min(50, Math.max(1, parseInt(limitParam || '5', 10) || 5)) const skip = (page - 1) * limit", file: "app/api/ab-test/route.ts" },
    { path: "/api/ab-test", method: "GET", doc: "ABテスト一覧を取得（ページネーション対応: デフォルト5件/ページ） /", file: "app/api/ab-test/route.ts" },
    { path: "/api/ab-test", method: "POST", doc: "ABテスト一覧を取得（ページネーション対応: デフォルト5件/ページ） / export async function GET(request: Request) { try { const { searchParams } = new URL(request.url) const productId = searchParams.get('productId') const status = searchParams.get('status') const pageParam = searchParams.get('page') const limitParam = searchParams.get('limit') const page = Math.max(1, parseInt(pageParam || '1', 10) || 1) const limit = Math.min(50, Math.max(1, parseInt(limitParam || '5', 10) || 5)) const skip = (page - 1) * limit", file: "app/api/ab-test/route.ts" },
    { path: "/api/ab-test", method: "PUT", doc: "ABテスト一覧を取得（ページネーション対応: デフォルト5件/ページ） / export async function GET(request: Request) { try { const { searchParams } = new URL(request.url) const productId = searchParams.get('productId') const status = searchParams.get('status') const pageParam = searchParams.get('page') const limitParam = searchParams.get('limit') const page = Math.max(1, parseInt(pageParam || '1', 10) || 1) const limit = Math.min(50, Math.max(1, parseInt(limitParam || '5', 10) || 5)) const skip = (page - 1) * limit", file: "app/api/ab-test/route.ts" },
    { path: "/api/ab-test/[id]", method: "GET", doc: "ABテスト詳細を取得 /", file: "app/api/ab-test/[id]/route.ts" },
    { path: "/api/ab-test/[id]/current", method: "GET", doc: "", file: "app/api/ab-test/[id]/current/route.ts" },
    { path: "/api/ab-test/[id]/daily", method: "POST", doc: "", file: "app/api/ab-test/[id]/daily/route.ts" },
    { path: "/api/ab-test/[id]/final-report", method: "POST", doc: "AI最終レポートを追加観点付きで再生成する。 body: { perspective?: string }  空文字/未指定なら観点をクリアして再生成 /", file: "app/api/ab-test/[id]/final-report/route.ts" },
    { path: "/api/ab-test/[id]/funnel", method: "GET", doc: "", file: "app/api/ab-test/[id]/funnel/route.ts" },
    { path: "/api/ab-test/[id]/next-execution", method: "GET", doc: "ABテストの次回実行予定日時を取得 /", file: "app/api/ab-test/[id]/next-execution/route.ts" },
    { path: "/api/ab-test/[id]/segment", method: "POST", doc: "", file: "app/api/ab-test/[id]/segment/route.ts" },
    { path: "/api/ab-test/[id]/status", method: "PUT", doc: "直近の実行結果から勝利バリアントとA比改善率を算出 / function getWinnerFromResultData(resultData: unknown): { winnerVariant: string | null; improvementVsAPercent: number | null } { const data = resultData as { cvrResults?: Record<string, { cvr: number; pv: number; cv: number }> } | null if (!data?.cvrResults) return { winnerVariant: null, improvementVsAPercent: null } const cvrResults = data.cvrResults const variants = [ cvrResults.dataA && { name: 'A', data: cvrResults.dataA }, cvrResults.dataB && { name: 'B', data: cvrResults.dataB }, cvrResults.dataC && { name: 'C', data: cvrResults.dataC }, cvrResults.dataD && { name: 'D', data: cvrResults.dataD }, ].filter(Boolean) as Array<{ name: string; data: { cvr: number } }> if (variants.length < 2) return { winnerVariant: null, improvementVsAPercent: null } variants.sort((a, b) => b.data.cvr - a.data.cvr) const winner = variants[0] const variantA = variants.find((v) => v.name === 'A') let improvementVsAPercent: number | null = null if (variantA && winner.name !== 'A' && variantA.data.cvr > 0) { improvementVsAPercent = (winner.data.cvr - variantA.data.cvr) / variantA.data.cvr * 100 } return { winnerVariant: winner.name, improvementVsAPercent } }", file: "app/api/ab-test/[id]/status/route.ts" },
    { path: "/api/ab-test/advisor", method: "POST", doc: "", file: "app/api/ab-test/advisor/route.ts" },
    { path: "/api/ab-test/check-webhook", method: "GET", doc: "Slack Webhook設定の確認 /", file: "app/api/ab-test/check-webhook/route.ts" },
    { path: "/api/ab-test/evaluate", method: "POST", doc: "ABテスト評価API", file: "app/api/ab-test/evaluate/route.ts" },
    { path: "/api/ab-test/execute", method: "POST", doc: "ABテスト自動実行API 期間終了後のABテストに対してGA4分析を実行する。abTestId 指定で 1 件だけ手動実行（force で同日スキップを無視）。 処理本体は lib/services/ab-test/execution/executeAbTests.ts /", file: "app/api/ab-test/execute/route.ts" },
    { path: "/api/ab-test/history", method: "GET", doc: "ABテスト実行履歴一覧を取得 /", file: "app/api/ab-test/history/route.ts" },
    { path: "/api/ab-test/test-execute", method: "POST", doc: "ABテストテスト実行API フォーム入力値で実際にGA4データを取得してCVRを計算し、問題がないか確認 データベースには保存しない /", file: "app/api/ab-test/test-execute/route.ts" },
    { path: "/api/ai-usage", method: "GET", doc: "", file: "app/api/ai-usage/route.ts" },
    { path: "/api/alerts/config", method: "GET", doc: "全プロダクトのアラート設定を返す（未設定のプロダクトはデフォルト値） */", file: "app/api/alerts/config/route.ts" },
    { path: "/api/alerts/config", method: "PUT", doc: "全プロダクトのアラート設定を返す（未設定のプロダクトはデフォルト値） */ export async function GET() { try { const products = await prisma.product.findMany({ where: { ga4PropertyId: { not: null } }, include: { alertConfig: true }, orderBy: { id: 'asc' }, }) const configs = products.map((p) => ({ productId: p.id, productName: p.name, enabled: p.alertConfig?.enabled ?? true, dropThreshold: p.alertConfig?.dropThreshold ?? DEFAULT_ALERT_CONFIG.dropThreshold, minSessions: p.alertConfig?.minSessions ?? DEFAULT_ALERT_CONFIG.minSessions, minCv: p.alertConfig?.minCv ?? DEFAULT_ALERT_CONFIG.minCv, metrics: Array.isArray(p.alertConfig?.metrics) ? p.alertConfig?.metrics : null, })) return NextResponse.json({ configs }) } catch (e) { console.error('[alertConfig] 取得失敗:', e) return NextResponse.json({ error: e instanceof Error ? e.message : 'error' }, { status: 500 }) } }", file: "app/api/alerts/config/route.ts" },
    { path: "/api/alerts/cv-drop", method: "POST", doc: "", file: "app/api/alerts/cv-drop/route.ts" },
    { path: "/api/alerts/seo-watch", method: "POST", doc: "", file: "app/api/alerts/seo-watch/route.ts" },
    { path: "/api/analytics/data", method: "POST", doc: "GA4 データ閲覧: 画面で指定した metrics / dimensions / filter をそのまま投げてテーブルで返す */", file: "app/api/analytics/data/route.ts" },
    { path: "/api/analytics/report", method: "POST", doc: "GA4 分析（レポートビルダー）の実行。クエリ → CVR → AB 判定 → 保存。 処理本体は lib/services/analytics/reportGenerationService.ts /", file: "app/api/analytics/report/route.ts" },
    { path: "/api/applications/actual", method: "POST", doc: "応募の全体像（DynamoDB 実数）。propertyId は任意で、あれば単独登録（GA4）も返す。 集計は lib/services/cv/applicationsActualService.ts /", file: "app/api/applications/actual/route.ts" },
    { path: "/api/auth/login", method: "POST", doc: "", file: "app/api/auth/login/route.ts" },
    { path: "/api/auth/logout", method: "POST", doc: "", file: "app/api/auth/logout/route.ts" },
    { path: "/api/business-kpi", method: "POST", doc: "応募数・会員登録数の月次（プロダクトDBが正）。propertyId を渡すとフォーム完了率（GA4）も付く。 集計は lib/services/kpi/businessKpiService.ts /", file: "app/api/business-kpi/route.ts" },
    { path: "/api/cv-types", method: "POST", doc: "求人種別（人材紹介 / 求人広告 / ハローワーク）× ステージの CV 分解。集計は lib/services/cv/cvTypesService.ts */", file: "app/api/cv-types/route.ts" },
    { path: "/api/cv-types/route-funnel", method: "POST", doc: "一覧経由 vs 直接着地の経路別ファネル（GA4 v1alpha）。集計は lib/services/cv/routeFunnelService.ts */", file: "app/api/cv-types/route-funnel/route.ts" },
    { path: "/api/dashboard", method: "GET", doc: "", file: "app/api/dashboard/route.ts" },
    { path: "/api/dashboard/page-cv-config", method: "GET", doc: "パスごとのCVイベント名設定の取得・保存", file: "app/api/dashboard/page-cv-config/route.ts" },
    { path: "/api/dashboard/page-cv-config", method: "POST", doc: "パスごとのCVイベント名設定の取得・保存", file: "app/api/dashboard/page-cv-config/route.ts" },
    { path: "/api/dashboard/page-metrics", method: "POST", doc: "指定ページパスの GA4 指標（PV, CV, CVR, 離脱率, 新規訪問率, 直帰数, 平均滞在時間 など）。 month（YYYY-MM）があればその月、無ければ startDate / endDate（既定 28daysAgo〜yesterday）。 集計は lib/services/dashboard/pageMetricsService.ts /", file: "app/api/dashboard/page-metrics/route.ts" },
    { path: "/api/dashboard/page-metrics/series", method: "POST", doc: "ページパスの時系列（日別・週別・月別）。 startDate / endDate（YYYY-MM-DD）が揃っていればそれを、無ければ month から集計単位に応じた期間を作る。 集計は lib/services/dashboard/pageMetricsService.ts /", file: "app/api/dashboard/page-metrics/series/route.ts" },
    { path: "/api/delivery-report", method: "POST", doc: "SMS・メール・LINE の配信実績を施策別／件名別に横断集計（社内宛のテスト配信は既定で除外）。集計は lib/services/delivery/deliveryReportService.ts */", file: "app/api/delivery-report/route.ts" },
    { path: "/api/docs/ask", method: "POST", doc: "", file: "app/api/docs/ask/route.ts" },
    { path: "/api/exit", method: "POST", doc: "ページカテゴリで組んだファネルの離脱状況。集計は lib/services/journey/exitService.ts */", file: "app/api/exit/route.ts" },
    { path: "/api/exit/gemini", method: "POST", doc: "", file: "app/api/exit/gemini/route.ts" },
    { path: "/api/funnel/engagement", method: "POST", doc: "エンゲージメントファネル分析API 元のGASコードのcreateEngagementFunnelReportを参考に実装 ページごと・滞在時間（time_on_page）のファネルを集計", file: "app/api/funnel/engagement/route.ts" },
    { path: "/api/funnel/engagement/page-paths", method: "POST", doc: "エンゲージメントファネルで取得しているページパス一覧を返す ダッシュボードのページ選択などで利用", file: "app/api/funnel/engagement/page-paths/route.ts" },
    { path: "/api/funnel/engagement/summary", method: "POST", doc: "", file: "app/api/funnel/engagement/summary/route.ts" },
    { path: "/api/funnel/entry-form", method: "POST", doc: "エントリーフォームファネル分析API 元のGASコードのcreateEntryFormFunnelReport関数を参考に実装", file: "app/api/funnel/entry-form/route.ts" },
    { path: "/api/funnel/entry-form/compare", method: "POST", doc: "", file: "app/api/funnel/entry-form/compare/route.ts" },
    { path: "/api/funnel/executions", method: "GET", doc: "ファネル実行履歴API", file: "app/api/funnel/executions/route.ts" },
    { path: "/api/funnel/executions", method: "POST", doc: "ファネル実行履歴API", file: "app/api/funnel/executions/route.ts" },
    { path: "/api/funnel/executions/[id]", method: "DELETE", doc: "ファネル実行履歴詳細API", file: "app/api/funnel/executions/[id]/route.ts" },
    { path: "/api/funnel/executions/[id]", method: "GET", doc: "ファネル実行履歴詳細API", file: "app/api/funnel/executions/[id]/route.ts" },
    { path: "/api/funnel/path", method: "POST", doc: "ページ閲覧とクリックタグを自由に並べた順序付きクローズドファネル（GA4 v1alpha） */", file: "app/api/funnel/path/route.ts" },
    { path: "/api/ga4/labels", method: "GET", doc: "click_label / view_label の値一覧（直近 90 日）。LabelContext が補完候補に使う */", file: "app/api/ga4/labels/route.ts" },
    { path: "/api/ga4/metadata", method: "GET", doc: "プロパティで使えるメトリクス・ディメンション一覧（GA4 メタデータページ） */", file: "app/api/ga4/metadata/route.ts" },
    { path: "/api/heatmap/page-paths", method: "POST", doc: "view_label が付いたイベントのあるページパス一覧。集計は lib/services/heatmap/heatmapService.ts */", file: "app/api/heatmap/page-paths/route.ts" },
    { path: "/api/heatmap/view-labels", method: "POST", doc: "view ラベル別イベント数（デバイス別）。ヒートマップページのデータソース。 集計は lib/services/heatmap/heatmapService.ts /", file: "app/api/heatmap/view-labels/route.ts" },
    { path: "/api/insights", method: "POST", doc: "月次インサイト（基準月の KPI・前月比・週次・12 ヶ月トレンド）。集計は lib/services/insights/insightsService.ts */", file: "app/api/insights/route.ts" },
    { path: "/api/insights/gemini", method: "POST", doc: "", file: "app/api/insights/gemini/route.ts" },
    { path: "/api/journey", method: "POST", doc: "ゴール到達までの経路（チャネル → N-2 → N-1 → ゴール）。集計は lib/services/journey/journeyService.ts */", file: "app/api/journey/route.ts" },
    { path: "/api/journey/gemini", method: "POST", doc: "", file: "app/api/journey/gemini/route.ts" },
    { path: "/api/line-report", method: "POST", doc: "LINE 経由の再訪・CV（GA4）と配信実績（BQ）。集計は lib/services/channel/lineReportService.ts */", file: "app/api/line-report/route.ts" },
    { path: "/api/line-report/associations", method: "POST", doc: "サイト → LINE連携の導線別クリック（BigQuery events_* 直接集計）。 同じ /line-report でも既存セクションはGA4 Data APIなので、重いBQクエリを巻き込まないよう エンドポイントを分けている（ページ側で並列に叩く）。 データソースは x-work.jp のGA4 BQエクスポート固定のため propertyId は不要。 /", file: "app/api/line-report/associations/route.ts" },
    { path: "/api/list-performance", method: "POST", doc: "求人一覧パフォーマンス（BigQuery）。 データソースは x-work.jp のエクスポート固定のため propertyId は不要。集計は listPerformanceService。 /", file: "app/api/list-performance/route.ts" },
    { path: "/api/occupation", method: "POST", doc: "職種別 会員登録CV・登録率・LP応募CV。集計は lib/services/cv/occupationService.ts */", file: "app/api/occupation/route.ts" },
    { path: "/api/occupation/detail", method: "POST", doc: "職種 URL 配下のセッション内訳。集計は lib/services/cv/occupationDetailService.ts */", file: "app/api/occupation/detail/route.ts" },
    { path: "/api/occupation/gemini", method: "POST", doc: "", file: "app/api/occupation/gemini/route.ts" },
    { path: "/api/pageflow", method: "POST", doc: "指定ページの直前・直後ページ。集計は lib/services/journey/pageFlowService.ts */", file: "app/api/pageflow/route.ts" },
    { path: "/api/product-goals", method: "DELETE", doc: "プロダクト目標の一覧。目標が無ければ初期テンプレートを入れて返す */ export async function GET(request: Request) { try { const productId = parseProductId(new URL(request.url).searchParams.get('productId')) const { goals, seeded } = await listProductGoals(productId) return NextResponse.json({ success: true, goals, seeded }) } catch (error) { return errorResponse(error, 'プロダクト目標の取得に失敗しました', 'Product Goals API Error', { withMessage: true }) } }", file: "app/api/product-goals/route.ts" },
    { path: "/api/product-goals", method: "GET", doc: "プロダクト目標の一覧。目標が無ければ初期テンプレートを入れて返す */", file: "app/api/product-goals/route.ts" },
    { path: "/api/product-goals", method: "PUT", doc: "プロダクト目標の一覧。目標が無ければ初期テンプレートを入れて返す */ export async function GET(request: Request) { try { const productId = parseProductId(new URL(request.url).searchParams.get('productId')) const { goals, seeded } = await listProductGoals(productId) return NextResponse.json({ success: true, goals, seeded }) } catch (error) { return errorResponse(error, 'プロダクト目標の取得に失敗しました', 'Product Goals API Error', { withMessage: true }) } }", file: "app/api/product-goals/route.ts" },
    { path: "/api/products", method: "DELETE", doc: "プロダクト管理API", file: "app/api/products/route.ts" },
    { path: "/api/products", method: "GET", doc: "プロダクト管理API", file: "app/api/products/route.ts" },
    { path: "/api/products", method: "POST", doc: "プロダクト管理API", file: "app/api/products/route.ts" },
    { path: "/api/products", method: "PUT", doc: "プロダクト管理API", file: "app/api/products/route.ts" },
    { path: "/api/reports", method: "GET", doc: "レポート一覧取得API", file: "app/api/reports/route.ts" },
    { path: "/api/reports/[id]", method: "GET", doc: "レポート詳細取得API", file: "app/api/reports/[id]/route.ts" },
    { path: "/api/reports/[id]/execution-mode", method: "PATCH", doc: "レポートの実行モードを更新するAPI", file: "app/api/reports/[id]/execution-mode/route.ts" },
    { path: "/api/reports/history", method: "GET", doc: "レポート履歴一覧取得API", file: "app/api/reports/history/route.ts" },
    { path: "/api/reports/history/[id]", method: "DELETE", doc: "レポート実行履歴削除API", file: "app/api/reports/history/[id]/route.ts" },
    { path: "/api/reports/weekly-summary", method: "POST", doc: "", file: "app/api/reports/weekly-summary/route.ts" },
    { path: "/api/scout/funnel", method: "POST", doc: "スカウト送信（DynamoDB）→ 閲覧 → 応募（GA4）のファネル。集計は lib/services/scout/scoutFunnelService.ts */", file: "app/api/scout/funnel/route.ts" },
    { path: "/api/seo-report", method: "POST", doc: "Search Console の掲載順位・表示・CTR・クリック（カテゴリ別・前期間比）。集計は lib/services/seo/seoReportService.ts */", file: "app/api/seo-report/route.ts" },
    { path: "/api/signup-funnel", method: "POST", doc: "会員登録フォームの質問別ファネル（ラベル自動復元）。集計は lib/services/signupFunnel */", file: "app/api/signup-funnel/route.ts" },
    { path: "/api/signup-funnel/trend", method: "POST", doc: "会員登録フォームの日別推移（職種別×全体）。集計は lib/services/signupFunnel */", file: "app/api/signup-funnel/trend/route.ts" },
    { path: "/api/signup-step-mails", method: "POST", doc: "会員登録後ステップメールの送信数・開封率。集計は lib/services/signupStepMails/signupStepMailsService.ts */", file: "app/api/signup-step-mails/route.ts" },
    { path: "/api/trend/monthly", method: "POST", doc: "月次トレンドレポート生成API", file: "app/api/trend/monthly/route.ts" },
    { path: "/api/trend/summary", method: "POST", doc: "", file: "app/api/trend/summary/route.ts" },
    { path: "/api/user-flow", method: "POST", doc: "", file: "app/api/user-flow/route.ts" },
    { path: "/api/user/cohort", method: "POST", doc: "初回訪問週ごとの週次リテンション。既定期間は今日までの 77 日（約 11 週） */", file: "app/api/user/cohort/route.ts" },
    { path: "/api/user/list", method: "POST", doc: "セグメント一覧（既定期間 30daysAgo〜today、limit 既定 10000） */", file: "app/api/user/list/route.ts" },
    { path: "/api/user/scoring", method: "POST", doc: "セグメント軸別の活動スコア。 期間は startDate / endDate 優先、無ければ periodDays（既定 30）から今日までを使う。 /", file: "app/api/user/scoring/route.ts" },
    { path: "/api/user/scoring/gemini", method: "POST", doc: "", file: "app/api/user/scoring/gemini/route.ts" },
    { path: "/api/user/segment-builder", method: "POST", doc: "AND 条件で定義したセグメントの集計。既定期間は今日までの 30 日 */", file: "app/api/user/segment-builder/route.ts" },
    { path: "/api/user/stickiness", method: "POST", doc: "DAU / WAU / MAU とスティッキネス。compareStartDate / compareEndDate で比較期間も返す */", file: "app/api/user/stickiness/route.ts" },
    { path: "/api/user/stickiness/gemini", method: "POST", doc: "", file: "app/api/user/stickiness/gemini/route.ts" },
    { path: "/api/user/timeline", method: "POST", doc: "セグメント条件に一致するイベントのタイムライン（既定期間 30daysAgo〜today） */", file: "app/api/user/timeline/route.ts" },
    { path: "/api/utm-report", method: "POST", doc: "UTM 4 軸別のセッション・ユーザー・CV。集計は lib/services/channel/utmReportService.ts */", file: "app/api/utm-report/route.ts" },
]
